package no.nav.pale

enum class PaleConstant(val string: String) {
    LE("LE"),
    LEGEERKL("LEGEERKL"),
    legeerklæring("legeerklæring"),
    Legeerklæring("Legeerklæring"),
    APPREC("APPREC"),
    APPRECVersionV1_0("1.0 2004-11-21"),
    ebRoleNav("Nav"),
    ebServiceLegemelding("Legemelding"),
    ebActionSvarmelding("Svarmelding"),
    eiaAuto("EIA_AUTO"),
    eiaOk("EIA_OK"),
    eiaMan("EIA_MAN"),
    pdf("PDF"),
    eia("EIA"),
    person("PERSON"),
    opp("OPP"),
    vedlegg("VEDLEGG"),
    arkiv("ARKIV"),
    kategoriKodeES("ES"),
    brevkode900002("900002"),
    behandlingsVeddleggTittel("legeerklæring-behandlingsvedlegg"),
    houveddokument("HOVEDDOKUMENT"),
    journalstatusKodeMO("MO"),
    journalposttypeKodeI("I"),
    pdfType(".pdf"),
    tilvurdering("TIL_VURDERING"),
    mappetypeRP("RP"),
    mappetypeUP("UP"),
    mappetypeYA("YA"),
    mappetypeSP("SP"),
    versjon2_0("2.0"),
    DNR("DNR"),
    FNR("FNR"),
    OPPFØLGING("OPPFØLGING")
}
